# Generated by Django 5.2 on 2025-05-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_alter_application_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(upload_to='media/'),
        ),
    ]
